 alias gss "git status -s"
 abbr g git
 abbr ga 'git add'
 alias gaa 'git add --all'
 abbr gap 'git apply'
 alias gapa 'git add --patch'
 alias gau 'git add --update'
 abbr gb 'git branch'
 alias gba 'git branch -a'
 abbr gbd 'git branch -d'
 # alias gbda 'git branch --no-color --merged | command grep -vE "^\(\*|\s*(master|develop|dev\)\s*$\)" | command xargs -n 1 git branch -d'
 alias gbl 'git blame -b -w'
 alias gbnm 'git branch --no-merged'
 alias gbr 'git branch --remote'
 abbr gbs 'git bisect'
 abbr gbsb 'git bisect bad'
 abbr gbsg 'git bisect good'
 abbr gbsr 'git bisect reset'
 abbr gbss 'git bisect start'
 alias gc 'git commit -v'
 alias 'gc!' 'git commit -v --amend'
 alias gca 'git commit -v -a'
 alias 'gca!' 'git commit -v -a --amend'
 alias gcam 'git commit -a -m'
 alias 'gcan!' 'git commit -v -a --no-edit --amend'
 alias 'gcans!' 'git commit -v -a -s --no-edit --amend'
 alias gcb 'git checkout -b'
 abbr gcd 'git checkout develop'
 alias gcf 'git config --list'
 alias gcl 'git clone --recursive'
 alias gclean 'git clean -fd'
 # alias gclm 'git fetch origin; git branch --merged | grep -v '\''\*\|master'\'' | xargs -n 1 git branch -d'
 abbr gcm 'git checkout master'
 alias gcmsg 'git commit -m'
 alias 'gcn!' 'git commit -v --no-edit --amend'
 abbr gco 'git checkout'
 alias gcount 'git shortlog -sn'
 abbr gcp 'git cherry-pick'
 alias gcpa 'git cherry-pick --abort'
 alias gcpc 'git cherry-pick --continue'
 alias gcs 'git commit -S'
 alias gcsm 'git commit -s -m'
 alias gd 'git diff -w --word-diff'
 alias gdca 'git diff --cached'
 alias gdct 'git describe --tags `git rev-list --tags --max-count 1`'
 alias gdcw 'git diff --cached --word-diff'
 alias gds 'git diff --staged -w --word-diff'
 alias gdt 'git diff-tree --no-commit-id --name-only -r'
 alias gdw 'git diff --word-diff'
 abbr gf 'git fetch'
 alias gfa 'git fetch --all --prune'
 abbr gfo 'git fetch origin'
 abbr gg 'git gui citool'
 alias gga 'git gui citool --amend'
 alias ggpull 'git pull origin (git_current_branch)'
 alias ggpush 'git push origin (git_current_branch)'
 alias ggsup 'git branch --set-upstream-to origin/(git_current_branch)'
 abbr ghh 'git help'
 alias gignore 'git update-index --assume-unchanged'
 alias gignored 'git ls-files -v | grep "^[[:lower:]]"'
 abbr gist 'nocorrect gist'
 # alias git-svn-dcommit-push 'git svn dcommit && git push github master:svntrunk'
 alias gk '\gitk --all --branches'
 alias gke '\gitk --all (git log -g --pretty %h)'
 abbr gl 'git pull'
 alias glg 'git log --stat'
 alias glgg 'git log --graph'
 alias glgga 'git log --graph --decorate --all'
 alias glgm 'git log --graph --max-count 10'
 alias glgp 'git log --stat -p'
 alias glo 'git log --oneline --decorate'
 abbr globurl 'noglob urlglobber '
 alias glog 'git log --oneline --decorate --graph'
 alias gloga 'git log --oneline --decorate --graph --all'
 # alias glol 'git log --graph --pretty '\''%Cred%h%Creset -%C\(yellow\)%d%Creset %s %Cgreen\(%cr\) %C\(bold blue\)<%an>%Creset'\'' --abbrev-commit'
 # alias glola 'git log --graph --pretty '\''%Cred%h%Creset -%C\(yellow\)%d%Creset %s %Cgreen\(%cr\) %C\(bold blue\)<%an>%Creset'\'' --abbrev-commit --all'
 # alias glp _git_log_prettily
 abbr glum 'git pull upstream master'
 abbr gm 'git merge'
 alias gma 'git merge --abort'
 alias gmom 'git merge origin/master'
 alias gmt 'git mergetool --no-prompt'
 alias gmtvim 'git mergetool --no-prompt --tool vimdiff'
 alias gmum 'git merge upstream/master'
 # alias goops 'git reset --soft HEAD^ && git stash save --keep-index && git pull origin  && git stash pop && git commit -m '
 abbr gp 'git push'
 alias gpd 'git push --dry-run'
 # alias gpoat 'git push origin --all && git push origin --tags'
 # alias gpristine 'git reset --hard && git clean -dfx'
 alias gpsup 'git push --set-upstream origin (git_current_branch)'
 abbr gpu 'git push upstream'
 alias gpv 'git push -v'
 abbr gr 'git remote'
 abbr gra 'git remote add'
 abbr grb 'git rebase'
 alias grba 'git rebase --abort'
 alias grbc 'git rebase --continue'
 alias grbi 'git rebase -i'
 abbr grbm 'git rebase master'
 alias grbs 'git rebase --skip'
 # alias grep 'grep  --color auto --exclude-dir {.bzr,CVS,.git,.hg,.svn}'
 alias grh 'git reset HEAD'
 alias grhh 'git reset HEAD --hard'
 abbr grmv 'git remote rename'
 abbr grrm 'git remote remove'
 abbr grset 'git remote set-url'
 # alias grt 'cd (git rev-parse --show-toplevel || echo ".")'
 alias gru 'git reset --'
 abbr grup 'git remote update'
 alias grv 'git remote -v'
 alias gsb 'git status -sb'
 abbr gsd 'git svn dcommit'
 abbr gsi 'git submodule init'
 alias gsps 'git show --pretty short --show-signature'
 abbr gsr 'git svn rebase'
 alias gss 'git status -s'
 abbr gst 'git status'
 abbr gsta 'git stash save'
 abbr gstaa 'git stash apply'
 abbr gstc 'git stash clear'
 abbr gstd 'git stash drop'
 abbr gstl 'git stash list'
 abbr gstp 'git stash pop'
 alias gsts 'git stash show --text'
 abbr gsu 'git submodule update'
 alias gts 'git tag -s'
 alias gtv 'git tag | sort -V'
 alias gunignore 'git update-index --no-assume-unchanged'
 alias gunwip 'git log -n 1 | grep -q -c "\-\-wip\-\-"; and git reset HEAD~1'
 alias gup 'git pull --rebase'
 alias gupv 'git pull --rebase -v'
 alias gwch 'git whatchanged -p --abbrev-commit --pretty medium'
 alias gwip 'git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'